#!/bin/env ruby
# encoding: utf-8

# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
{
:name => "ignite-proxy",
:eth1 => "192.168.5.10",
:mem => "1500",
:cpu => "2",
:box => "ubuntu/trusty64",
:shells => [
    "shells/system/copydebs.sh",
    "shells/system/aptupdate.sh",
    "shells/system/apt.sh",
    "shells/system/generic.sh",
    "shells/system/ssh.sh",
    "shells/system/nginxinstall.sh"
],
:files => [
{
    :src => "files/resources/archives.zip",
    :dst => "/home/vagrant/archives.zip"},  
{
    :src => "files/resources/nginx.conf",
    :dst => "/home/vagrant/nginx.conf"},  
{
    :src => "files/system",
    :dst => "/home/vagrant"}
],
:ports_forward => [
{
:guest => 8088, :host => 8089}
]
},
{
:name => "ignite-1",
:eth1 => "192.168.5.11",
:mem => "2000",
:cpu => "1",
:box => "ubuntu/trusty64",
:shells => [
    "shells/system/copydebs.sh",
    "shells/system/aptupdate.sh",
   "shells/system/apt.sh",
    "shells/system/generic.sh",
    "shells/system/ssh.sh",
    "shells/system/igniteinstall.sh",
    "shells/system/tomcat.sh"
],
:files => [
{
    :src => "files/tasks/ROOT.war",
    :dst => "/home/vagrant/ROOT.war"},
{
    :src => "files/resources/archives.zip",
    :dst => "/home/vagrant/archives.zip"},  
{
    :src => "files/resources/apache-ignite-fabric-1.9.0-bin.zip",
    :dst => "/home/vagrant/apache-ignite-fabric-1.9.0-bin.zip"},  
{
    :src => "files/resources/my-config.xml",
    :dst => "/home/vagrant/my-config.xml"}, 
{
    :src => "files/resources/deploy.sh",
    :dst => "/home/vagrant/deploy.sh"}, 
{
    :src => "files/resources/startignite.sh",
    :dst => "/home/vagrant/startignite.sh"}, 
{
    :src => "files/resources/tomcat7",
    :dst => "/home/vagrant/tomcat7"}, 
{
    :src => "files/system",
    :dst => "/home/vagrant"}
],
:ports_forward => [
{
:guest => 8080, :host => 8090}
]
},
{
:name => "ignite-2",
:eth1 => "192.168.5.12",
:mem => "2000",
:cpu => "1",
:box => "ubuntu/trusty64",
:shells => [
    "shells/system/copydebs.sh",
    "shells/system/aptupdate.sh",
   "shells/system/apt.sh",
    "shells/system/generic.sh",
    "shells/system/ssh.sh",
    "shells/system/igniteinstall.sh",
    "shells/system/tomcat.sh"
],
:files => [
{
    :src => "files/tasks/ROOT.war",
    :dst => "/home/vagrant/ROOT.war"},
{
    :src => "files/resources/archives.zip",
    :dst => "/home/vagrant/archives.zip"},  
{
    :src => "files/resources/apache-ignite-fabric-1.9.0-bin.zip",
    :dst => "/home/vagrant/apache-ignite-fabric-1.9.0-bin.zip"},  
{
    :src => "files/resources/my-config.xml",
    :dst => "/home/vagrant/my-config.xml"},
{
    :src => "files/resources/deploy.sh",
    :dst => "/home/vagrant/deploy.sh"}, 
{
    :src => "files/resources/startignite.sh",
    :dst => "/home/vagrant/startignite.sh"},  
{
    :src => "files/resources/tomcat7",
    :dst => "/home/vagrant/tomcat7"}, 
{
    :src => "files/system",
    :dst => "/home/vagrant"}
],
:ports_forward => [
{
:guest => 8088, :host => 8091}
]
}
]


Vagrant.configure(2) do |config|
    boxes.each do |opts|

        config.vm.define opts[:name] do |config|
            config.vbguest.auto_update = false
            config.vm.provider "virtualbox" do |v, override|
                override.vm.box = opts[:box]
            end
            config.vm.hostname = opts[:name]
            config.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
            end

            config.vm.network :private_network, ip: opts[:eth1]

            opts[:ports_forward].each do |item|
                config.vm.network "forwarded_port", guest: item[:guest], host: item[:host]
            end

            opts[:files].each do |fileitem|
                config.vm.provision :file do |file|
                    file.source = fileitem[:src]
                    file.destination = fileitem[:dst]
                end
            end
            opts[:shells].each do |item|
                config.vm.provision :shell, path: item
            end
        end
    end
end
